export const DEMO_STUDENT_PROFILE = {
  student_id: "stu_sujith_001",
  email: "sujith.dev@example.com",
  name: "Sujith V",
  academic: {
    education_level: "Undergraduate",
    degree: "B.Tech",
    department: "Computer Science & Engineering",
    college: "National Institute of Technology",
    graduation_year: 2027,
    cgpa: 8.8,
    max_cgpa: 10.0,
  },
  skills: ["Python", "AWS", "TypeScript", "React", "FastAPI", "Docker", "Machine Learning", "Node.js"],
  programming_languages: ["Python", "TypeScript", "JavaScript", "C++", "SQL"],
  interests: ["Cloud Computing", "Autonomous AI Agents", "Web Development", "Distributed Systems"],
  career_goals: ["AWS Cloud Engineer", "AI/ML Solutions Architect", "Full Stack Developer"],
  experience: [
    {
      role: "Cloud & AI Research Intern",
      organization: "TechInnovate Labs",
      duration: "Jun 2025 - Aug 2025",
      description: "Built serverless microservices using AWS Lambda, DynamoDB, and Bedrock LLM endpoints.",
    },
  ],
  projects: [
    {
      title: "OpportunityOS",
      tech_stack: ["FastAPI", "Next.js", "AWS Bedrock", "DynamoDB"],
      description: "Autonomous AI agent platform for student opportunity discovery and auto-filling.",
    },
  ],
  certifications: ["AWS Certified Cloud Practitioner", "Deep Learning Specialization (Coursera)"],
  preferences: {
    preferred_types: ["INTERNSHIP", "HACKATHON", "FELLOWSHIP", "SCHOLARSHIP"],
    preferred_locations: ["Remote", "Bengaluru", "Hyderabad", "United States"],
    remote_only: false,
    min_match_score: 70,
  },
};

export const DEMO_OPPORTUNITIES = [
  {
    opportunity_id: "opp_aws_cloud_01",
    title: "AWS Cloud Engineering Internship 2026",
    organization: "Amazon Web Services (AWS)",
    type: "INTERNSHIP",
    description:
      "Join AWS Cloud Solutions team to build distributed serverless automation systems, Bedrock AI integrations, and cloud infrastructure pipelines.",
    deadline: "2026-09-25",
    application_url: "https://aws.amazon.com/university/internships/cloud-2026",
    location: "Bengaluru / Remote",
    is_remote: true,
    stipend_or_reward: "₹85,000 / month + Relocation",
    eligibility_criteria: [
      "B.Tech/BE in Computer Science, IT or related field",
      "Graduation Year 2026 or 2027",
      "CGPA >= 7.5",
      "AWS & Python knowledge",
    ],
    requirements: ["Resume", "Transcript", "AWS Certification (Optional)", "Statement of Interest"],
    benefits: ["Mentorship from Senior Principal Engineers", "Full-time PPO conversion opportunity", "AWS Certification Vouchers"],
    overall_score: 94,
    source: "AgentCore Gateway - Amazon Careers Connector",
    score_breakdown: {
      eligibility_score: 94,
      relevance_score: 96,
      skill_match_score: 92,
      deadline_urgency_score: 88,
      opportunity_value_score: 95,
      explanation:
        "Your AWS and Python skills strongly match the technical requirements. Your cloud learning goal aligns directly with this opportunity.",
    },
  },
  {
    opportunity_id: "opp_ms_challenge_02",
    title: "Microsoft Imagine Student AI Challenge 2026",
    organization: "Microsoft",
    type: "HACKATHON",
    description: "Global student innovation contest to design agentic AI workflows on Azure Bedrock & OpenAI endpoints.",
    deadline: "2026-10-10",
    application_url: "https://imaginecup.microsoft.com/en-us/2026",
    location: "Global / Virtual",
    is_remote: true,
    stipend_or_reward: "$100,000 Grand Prize + Azure Credits",
    eligibility_criteria: ["Currently enrolled undergraduate student", "Team of 1 to 4 members", "Working prototype"],
    requirements: ["Resume", "Project Architecture Video", "GitHub Repository"],
    benefits: ["Global Recognition", "Direct Interview for Microsoft Garage", "$10,000 Cloud Credits"],
    overall_score: 91,
    source: "AgentCore Gateway - Microsoft Developer Portal",
    score_breakdown: {
      eligibility_score: 90,
      relevance_score: 94,
      skill_match_score: 90,
      deadline_urgency_score: 85,
      opportunity_value_score: 96,
      explanation: "Your hackathon experience and agent building skills fit the global Imagine Cup challenge requirements.",
    },
  },
  {
    opportunity_id: "opp_google_cloud_03",
    title: "Google Generation Cloud & AI Scholarship",
    organization: "Google",
    type: "SCHOLARSHIP",
    description: "Scholarship for computer science students demonstrating leadership, academic excellence, and passion for cloud technologies.",
    deadline: "2026-10-01",
    application_url: "https://buildyourfuture.withgoogle.com/scholarships",
    location: "India",
    is_remote: true,
    stipend_or_reward: "$2,500 Academic Grant",
    eligibility_criteria: ["Computer Science student", "CGPA >= 8.0", "Demonstrated community impact"],
    requirements: ["Resume", "Transcript", "2 Essays (300 words)", "Letter of Recommendation"],
    benefits: ["$2,500 Tuition Support", "Google Engineer Mentorship Retreat", "Community Summit Invite"],
    overall_score: 89,
    source: "AgentCore Gateway - Google Student Portal",
    score_breakdown: {
      eligibility_score: 92,
      relevance_score: 88,
      skill_match_score: 85,
      deadline_urgency_score: 85,
      opportunity_value_score: 92,
      explanation: "Your 8.8 CGPA exceeds the 8.0 requirement. Academic background strongly fits Google's grant criteria.",
    },
  },
  {
    opportunity_id: "opp_ai_innov_04",
    title: "National AI & Autonomous Systems Innovation Hackathon",
    organization: "NITI Aayog & AICTE",
    type: "HACKATHON",
    description: "36-hour national level hackathon focused on building autonomous agentic frameworks for public good.",
    deadline: "2026-09-20",
    application_url: "https://ai.gov.in/hackathons/2026",
    location: "Hyderabad / Remote",
    is_remote: true,
    stipend_or_reward: "₹3,000,000 Total Prize Pool",
    eligibility_criteria: ["Engineering Students across India", "Interest in AI / Agents / Cloud"],
    requirements: ["Resume", "Abstract Submission", "Team Roster"],
    benefits: ["Government Incubation Grant", "National Certificate", "Direct Internship Interviews"],
    overall_score: 95,
    source: "AgentCore Gateway - Govt Opportunities API",
  },
  {
    opportunity_id: "opp_wit_fellowship_05",
    title: "Women in Tech & Cloud Leadership Fellowship",
    organization: "Grace Hopper Foundation",
    type: "FELLOWSHIP",
    description: "6-month intensive fellowship providing mentorship, technical workshops, and cloud certification pathways.",
    deadline: "2026-10-15",
    application_url: "https://ghc.org/fellowships/2026",
    location: "Remote",
    is_remote: true,
    stipend_or_reward: "$1,500 Fellowship Stipend",
    eligibility_criteria: ["Undergraduate student in STEM", "Demonstrated leadership in campus tech clubs"],
    requirements: ["Resume", "Letter of Recommendation", "Statement of Purpose"],
    benefits: ["1-on-1 Executive Mentorship", "Full Conference Pass", "Certification Funding"],
    overall_score: 86,
    source: "AgentCore Gateway - GHC Connector",
  },
  {
    opportunity_id: "opp_open_source_06",
    title: "Linux Foundation Open Source Cloud Fellowship",
    organization: "Linux Foundation",
    type: "FELLOWSHIP",
    description: "Contribute to core open-source cloud native projects (Kubernetes, Envoy, OpenTelemetry) under expert guidance.",
    deadline: "2026-11-01",
    application_url: "https://lfx.linuxfoundation.org/mentorship",
    location: "Remote",
    is_remote: true,
    stipend_or_reward: "$3,000 Stipend over 12 weeks",
    eligibility_criteria: ["Strong Git, C++ or Go/Python skills", "Demonstrated open source contributions"],
    requirements: ["Resume", "GitHub Profile", "Project Proposal"],
    benefits: ["Stipend", "Global OSS Visibility", "Direct Hiring Referrals"],
    overall_score: 88,
    source: "AgentCore Gateway - LFX Portal",
  },
];

export const DEMO_APPLICATIONS = [
  {
    application_id: "app_aws_001",
    student_id: "stu_sujith_001",
    opportunity_id: "opp_aws_cloud_01",
    opportunity_title: "AWS Cloud Engineering Internship 2026",
    organization: "Amazon Web Services (AWS)",
    status: "AWAITING_APPROVAL",
    readiness_score: 85,
    overall_score: 94,
    deadline: "2026-09-25",
    required_documents: {
      Resume: "READY",
      Transcript: "READY",
      Certificate: "READY",
      Recommendation: "MISSING",
    },
    missing_documents: ["Recommendation Letter"],
    form_fields: [
      { field_id: "f_name", label: "Full Name", field_type: "text", value: "Sujith V", suggested_by_ai: true, is_user_edited: false, confidence: 1.0 },
      { field_id: "f_email", label: "Email Address", field_type: "text", value: "sujith.dev@example.com", suggested_by_ai: true, is_user_edited: false, confidence: 1.0 },
      { field_id: "f_college", label: "University / College", field_type: "text", value: "National Institute of Technology", suggested_by_ai: true, is_user_edited: false, confidence: 0.98 },
      { field_id: "f_cgpa", label: "CGPA / Percentage", field_type: "text", value: "8.8 / 10.0", suggested_by_ai: true, is_user_edited: false, confidence: 0.99 },
      { field_id: "f_skills", label: "Key Technical Skills", field_type: "text", value: "Python, AWS, TypeScript, React, FastAPI, Docker", suggested_by_ai: true, is_user_edited: false, confidence: 0.96 },
    ],
    generated_answers: [
      {
        question_id: "q_intro",
        question: "Tell us about yourself and your technical background.",
        answer: "I am Sujith V, a B.Tech Computer Science student at National Institute of Technology with an 8.8 CGPA. I specialize in Cloud Systems and Autonomous AI Agents, with hands-on experience building serverless microservices on AWS (Lambda, DynamoDB, Bedrock LLM endpoints).",
        approved: true,
        original_ai_answer: "I am Sujith V, a Computer Science student at NIT specializing in Cloud Systems.",
      },
      {
        question_id: "q_why_aws",
        question: "Why are you interested in joining AWS Cloud Solutions?",
        answer: "My career goal is to become an AWS Cloud Architect. Having built OpportunityOS leveraging Amazon Bedrock and serverless architecture, joining AWS directly aligns with my goal of engineering fault-tolerant cloud tools at global scale.",
        approved: true,
        original_ai_answer: "My career goal is to work with AWS Cloud Architecture.",
      },
    ],
  },
];

export const DEMO_DOCUMENTS = [
  {
    document_id: "doc_resume_01",
    student_id: "stu_sujith_001",
    name: "Sujith_V_Resume_2026.pdf",
    doc_type: "RESUME",
    s3_key: "students/stu_sujith_001/resume/Sujith_V_Resume_2026.pdf",
    s3_url: "https://opportunityos-student-documents-prod.s3.amazonaws.com/students/stu_sujith_001/resume/Sujith_V_Resume_2026.pdf",
    file_size_bytes: 102400,
    tags: ["resume", "latest"],
  },
  {
    document_id: "doc_transcript_01",
    student_id: "stu_sujith_001",
    name: "Official_Academic_Transcript_Sem6.pdf",
    doc_type: "TRANSCRIPT",
    s3_key: "students/stu_sujith_001/transcripts/Official_Academic_Transcript_Sem6.pdf",
    s3_url: "https://opportunityos-student-documents-prod.s3.amazonaws.com/students/stu_sujith_001/transcripts/Official_Academic_Transcript_Sem6.pdf",
    file_size_bytes: 204800,
    tags: ["transcript"],
  },
  {
    document_id: "doc_cert_aws_01",
    student_id: "stu_sujith_001",
    name: "AWS_Cloud_Practitioner_Certificate.pdf",
    doc_type: "CERTIFICATE",
    s3_key: "students/stu_sujith_001/certificates/AWS_Cloud_Practitioner_Certificate.pdf",
    s3_url: "https://opportunityos-student-documents-prod.s3.amazonaws.com/students/stu_sujith_001/certificates/AWS_Cloud_Practitioner_Certificate.pdf",
    file_size_bytes: 153600,
    tags: ["aws", "certification"],
  },
];

export const DEMO_ACTIVITIES = [
  { activity_id: "act_01", timestamp: "21:04", agent_name: "Discovery Agent", icon: "🔎", summary: "Scanned 6 active opportunity channels via AgentCore Gateway", details: { found: 6 } },
  { activity_id: "act_02", timestamp: "21:05", agent_name: "Verification Agent", icon: "🛡️", summary: "Verified URLs, deadlines, and active organization statuses", details: { verified: 6 } },
  { activity_id: "act_03", timestamp: "21:05", agent_name: "Deduplication Agent", icon: "⚡", summary: "Identified 0 duplicates using title & URL similarity matrix", details: { canonical_kept: 6 } },
  { activity_id: "act_04", timestamp: "21:06", agent_name: "Eligibility Agent", icon: "🧠", summary: "Evaluated Sujith V profile: 94% eligibility score for AWS Cloud Internship", details: { student_id: "stu_sujith_001" } },
  { activity_id: "act_05", timestamp: "21:06", agent_name: "Ranking Agent", icon: "✨", summary: "Ranked opportunities: AWS Cloud Internship placed in Top Priority", details: { top_match: "AWS Cloud Engineering Internship 2026" } },
  { activity_id: "act_06", timestamp: "21:07", agent_name: "Application Agent", icon: "📄", summary: "Prepared application answers & detected 1 missing document (Recommendation Letter)", details: { readiness_score: 85 } },
  { activity_id: "act_07", timestamp: "21:08", agent_name: "Browser Agent", icon: "🌐", summary: "AgentCore Browser mapped 18 form fields and paused awaiting human approval", details: { status: "AWAITING_APPROVAL" } },
];
